# Generated by Django 5.2.12 on 2026-03-28 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('question', models.TextField()),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('user_id', models.CharField(blank=True, max_length=128)),
                ('standards_scope', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=16)),
                ('mode', models.CharField(choices=[('faq', 'FAQ'), ('rag', 'RAG'), ('abstain', 'Abstain')], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('answer', models.TextField(blank=True)),
                ('abstained', models.BooleanField(default=False)),
                ('abstention_reason', models.CharField(blank=True, choices=[('INSUFFICIENT_EVIDENCE', 'Insufficient evidence'), ('POLICY_BLOCK', 'Policy block'), ('RETRIEVAL_LOW_QUALITY', 'Retrieval low quality'), ('UNKNOWN', 'Unknown')], max_length=64, null=True)),
                ('review_required', models.BooleanField(default=False)),
                ('matched_faq_entry_id', models.CharField(blank=True, max_length=128, null=True)),
                ('retrieval_event_ids', models.JSONField(blank=True, default=list)),
                ('evidence_link_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reason', models.CharField(choices=[('LOW_CONFIDENCE', 'Low confidence'), ('CITATION_GAP', 'Citation gap'), ('POLICY_REVIEW', 'Policy review'), ('USER_ESCALATION', 'User escalation')], max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review')], default='draft', max_length=16)),
                ('question_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_queue_items', to='helpdesk.questionevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
