# Generated by Django 5.2.12 on 2026-03-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository_url', models.URLField()),
                ('commit_sha', models.CharField(max_length=64)),
                ('source_path', models.CharField(max_length=512)),
                ('chunk_id', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('standards_scope', models.JSONField(blank=True, default=list)),
                ('quality_score', models.FloatField(default=0.5)),
            ],
            options={
                'ordering': ['-quality_score', 'source_path', 'chunk_id'],
                'indexes': [models.Index(fields=['repository_url'], name='helpdesk_so_reposit_863410_idx'), models.Index(fields=['source_path'], name='helpdesk_so_source__f74472_idx'), models.Index(fields=['quality_score'], name='helpdesk_so_quality_200d23_idx')],
            },
        ),
    ]
