# Generated by Django 5.2.12 on 2026-04-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_create_sourcechunk_vector_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcechunk',
            name='chunk_type',
            field=models.CharField(blank=True, default='prose', max_length=32),
        ),
        migrations.AddField(
            model_name='sourcechunk',
            name='heading',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
