# Generated by Django 5.2.12 on 2026-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_questionevent_engagement_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialqueueitem',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('published', 'Published')], default='in_review', max_length=16),
        ),
        migrations.AlterField(
            model_name='editorialqueuetransition',
            name='action',
            field=models.CharField(choices=[('request_changes', 'Request changes'), ('approve', 'Approve'), ('reject', 'Reject'), ('revoke', 'Revoke'), ('publish', 'Publish'), ('reopen', 'Reopen')], max_length=32),
        ),
        migrations.AlterField(
            model_name='editorialqueuetransition',
            name='from_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('published', 'Published')], max_length=16),
        ),
        migrations.AlterField(
            model_name='editorialqueuetransition',
            name='to_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked'), ('published', 'Published')], max_length=16),
        ),
    ]
