# Generated by Django 5.2.12 on 2026-06-29 15:11

from django.db import migrations


def fix_repository_urls(apps, schema_editor):
    """Extract base repository URL from full blob URLs in AnswerEvidenceLink."""
    AnswerEvidenceLink = apps.get_model('helpdesk', 'AnswerEvidenceLink')

    for link in AnswerEvidenceLink.objects.all():
        if '/blob/' in link.repository_url:
            # Extract base repo URL from full blob URL
            # e.g., "https://github.com/Owner/Repo/blob/ref/path" -> "https://github.com/Owner/Repo"
            base_url = link.repository_url.split('/blob/')[0]
            link.repository_url = base_url
            link.save()


def reverse_fix(apps, schema_editor):
    """Reverse is not applicable - we're fixing corrupted data."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_alter_editorialqueueitem_status_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_repository_urls, reverse_fix),
    ]
