# Generated by Django 5.2.12 on 2026-07-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_fix_repository_url_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionevent',
            name='trace',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
